[config]
schemaVersion = "0.0.1"

[package]
namespace = "nightkosh"
name = "BlindCartographer"
versionNumber = "1.0.3"
description = "Quality-of-life mod that enhances navigation, especially in "No Map" mode."
websiteUrl = "https://github.com/NightKosh/BlindCartographer"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "bin/Release/BlindCartographer.dll"
target = "plugins/BlindCartographer/BlindCartographer.dll"


categories = ["mods"]
community = "valheim"
